version: "3.8"

services:
  db_manager:
    container_name: db_manager
    build:
      context: ./services/db_manager
      dockerfile: Dockerfile.prod
      args:
        DB_MANAGER_APP_PATH: "${DB_MANAGER_APP_PATH}"
    env_file:
      - ./.env.prod
    depends_on:
      - db
    volumes:
      - "db_manager_logs:${DB_MANAGER_APP_PATH}${DB_MANAGER_APP_LOGS_DIR}/"
    environment:
      - "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN"
      - "TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID"
  db:
    container_name: postgres
    image: postgres:14.2-alpine
    env_file:
      - ./.env.prod
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  db_manager_logs:
