version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres:14.2-alpine
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dgtrv
      - POSTGRES_PASSWORD=dgtrv
      - POSTGRES_DB=heroes_db

volumes:
  postgres_data: