version: "3.8"

services:
  db_manager:
    container_name: db_manager
    build:
      context: ./services/db_manager
      args:
        DB_MANAGER_APP_PATH=${DB_MANAGER_APP_PATH}
    env_file:
      - ./.env.dev
    depends_on:
      - db
    volumes:
      - "${HOST_LOGS_DIR}:${DB_MANAGER_APP_PATH}${DB_MANAGER_APP_LOGS_DIR}/"
  db:
    container_name: postgres
    image: postgres:14.2-alpine
    env_file:
      - ./.env.dev
    ports:
      - "127.0.0.1:5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
